# This rule is not used by the project inference-scheduler-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over llm.llm-d.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inference-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
  name: inferencescheduler-admin-role
rules:
- apiGroups:
  - llm.llm-d.io
  resources:
  - inferenceschedulers
  verbs:
  - '*'
- apiGroups:
  - llm.llm-d.io
  resources:
  - inferenceschedulers/status
  verbs:
  - get
