# This rule is not used by the project inference-scheduler-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the llm.llm-d.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: inference-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
  name: inferencescheduler-editor-role
rules:
- apiGroups:
  - llm.llm-d.io
  resources:
  - inferenceschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llm.llm-d.io
  resources:
  - inferenceschedulers/status
  verbs:
  - get
