## Append samples of your project ##
resources:
- llm_v1alpha1_inferencescheduler.yaml
- llm_v1alpha1_inferencescheduler_minimal.yaml
- llm_v1alpha1_inferencescheduler_istio.yaml
- llm_v1alpha1_inferencescheduler_simulator.yaml
- llm_v1alpha1_inferencescheduler_simulator_minimal.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
